### ISSUE TITLE
make community meeting/events more discoverable

### ISSUE THREAD

**Issue by tjstansell** [cloud-custodian/community#28]
I would suggest figuring out where the canonical location for community resources should live and updating the various locations that reference the community to point to this central location.  cloudcustodian.io points folks to the gitter channel.  the cloud-custodian README.md has a section buried in it that asks folks to join the google group and links to the meeting archives on youtube and here.  I could not find anything that has a clear indication of _upcoming_ community events (meetings, cloud custodian day, etc).  I'd love to see a calendar of upcoming events, even if it's just a bullet list of things by date.  Basically, organize all of the community stuff into one place that's easy to find and easy to digest.  Given this new repo, the obvious choice would be to just update the README.md in this repo so it's front and center here.

**Comment by castrojo** [comment]
I've added the 2 upcoming 2021 events to the readme, This should be a proper /events page on the website, I can start to work on that. Some notes to self: 

- Proper calendar widget 
  - Should have easy click-to-subscribe functionality
  - Provide a raw ics link too
  - Easy url to remember cloud-custodian.io/events
  - The usual social stuff for people to share events
- A method for community people to submit things
- Include outside events that have attendance from the c7n community (reinvent) 
- If those events are recorded cross link to those resources so we can organize those better
- Appropriate CFP deadlines

**Comment by castrojo** [comment]
WIP: https://github.com/cloud-custodian/cloud-custodian/pull/6887

**Comment by castrojo** [comment]
Alright this is finished now!
